apiVersion: v1
kind: Pod
metadata:
 name: sqlserver
 labels:
  name: sqlserver
  app: sqlserver_dev
spec:
 volumes:
  - name: sql-pv-storage
    persistentVolumeClaim:
     claimName: sql-server-clone-pvc 
 containers:
  - name: sqlserver-container
    image: microsoft/mssql-server-linux:2017-latest
    ports:
    - containerPort: 1433
    env:
    - name: SA_PASSWORD
      value: "netapp-01"
    - name: ACCEPT_EULA
      value: "Y"
    volumeMounts:
    - mountPath: "/var/opt/mssql_clone"
      name: sql-pv-storage
 nodeSelector:
  ram_size: large 
--- 
kind: Service
apiVersion: v1
metadata:
  name: sqlserver-service
spec:
  ports:
  - protocol: "TCP"
    name: sqlserver
    port: 1433
    targetPort: 1433
    nodePort: 31433
  selector:
    name: sqlserver
  type: NodePort
